# Generated by Django 5.2.1 on 2025-10-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='description',
            new_name='account_description',
        ),
        migrations.RemoveField(
            model_name='account',
            name='code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.AddField(
            model_name='account',
            name='account_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Receivables', 'Receivables'), ('Payables', 'Payables'), ('Equity Capital', 'Equity Capital')], default='Cash', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='Asset', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Not Active')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='cost_center',
            field=models.CharField(blank=True, choices=[('construction', 'Construction'), ('sales', 'Sales'), ('finance', 'Finance'), ('admin', 'Administration'), ('hr', 'Human Resources')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('BDT', 'Bangladeshi Taka'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('GBP', 'British Pound')], default='USD', max_length=10),
        ),
    ]
