# Generated by Django 5.2.1 on 2025-09-28 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Client Name')),
                ('client_email', models.EmailField(max_length=254, unique=True, verbose_name='Client Email')),
                ('client_phone', models.CharField(max_length=15, unique=True, verbose_name='Client Phone')),
                ('client_address', models.TextField(blank=True, null=True, verbose_name='Client Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='Project Name')),
            ],
        ),
    ]
