name: Build and deploy Python app to Azure Web App - PERP-AC-App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install Django dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧠 Debug environment variables
        run: |
          echo "DATABASE_NAME=${{ env.DATABASE_NAME }}"
          echo "DATABASE_USER=${{ env.DATABASE_USER }}"
          echo "DATABASE_HOST=${{ env.DATABASE_HOST }}"

      - name: ✅ Django health check
        run: python manage.py check

      - name: 🔧 Django setup
        run: |
          python manage.py collectstatic --noinput --skip-checks
          python manage.py migrate

      - name: 📦 Package artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" "__pycache__/*" "*.pyc" "*.pyo" "*.db"

      - name: 📤 Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 📥 Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: 📂 Unzip artifact
        run: unzip release.zip

      - name: 🔐 Login to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 🚀 Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PERP-AC-App'
          slot-name: 'Production'
          package: release.zip




