"""
Django settings for erp_project project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

# 🧠 Core Imports
import os
import json
from pathlib import Path

# 📁 Base Directory
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔐 Security
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-9^6na*me7)=)1b3_zx1kggfe@b7j)c(thip)3&&bbg*395le=f')
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# 🌍 Hosts and CSRF — Hardened for Azure
try:
    ALLOWED_HOSTS = json.loads(os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        '["localhost", "127.0.0.1", "perp-ac-app.azurewebsites.net"]'
    ))
except (json.JSONDecodeError, TypeError):
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "perp-ac-app.azurewebsites.net"]

try:
    CSRF_TRUSTED_ORIGINS = json.loads(os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        '["https://perp-ac-app.azurewebsites.net"]'
    ))
except (json.JSONDecodeError, TypeError):
    CSRF_TRUSTED_ORIGINS = [
        "https://perp-ac-app.azurewebsites.net"
    ]

# 🔐 CSRF and Cookie Security for Azure
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False

# ✅ Trust Azure's HTTPS proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ⚠️ Prevent redirect loops: Let Azure handle HTTPS
SECURE_SSL_REDIRECT = False

# ✅ Optional: Enable HSTS headers only in production
SECURE_HSTS_SECONDS = 3600 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True


# 📦 Installed Apps
INSTALLED_APPS = [
    # Django Core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom Apps
    'home',
    'construction',
    'design',
    'project',
    'client',
    'accounts',
    'finance',
    'account',
]

# 🧱 Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.EnsureProfileAndDepartmentMiddleware',  # ✅ Custom middleware for profile and department mapping
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 🔐 Azure AD Department Mapping
DEPARTMENT_EMAIL_MAP = {
    # 👷 Abir has access to Construction
    'abir@dzignscapeprofessionals.onmicrosoft.com': ['construction'],
    # 🎨 Bokul has access to Design
    'bokul@dzignscapeprofessionals.onmicrosoft.com': ['design'],
    # 🛠️ Admin has access to all departments
    'admin@dzignscapeprofessionals.onmicrosoft.com': ['construction', 'design', 'finance'],
}

# 🔐 Azure AD Login Redirect
LOGIN_URL = '/.auth/login/aad'

# 🌐 URL & WSGI
ROOT_URLCONF = 'erp_project.urls'
WSGI_APPLICATION = 'erp_project.wsgi.application'

# 🧠 Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 🗄️ Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME'),
        'USER': os.environ.get('DATABASE_USER'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
        'HOST': os.environ.get('DATABASE_HOST'),
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}

# 🔐 Password Validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 🌍 Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Dhaka'
USE_I18N = True
USE_TZ = True

# 📦 Static Files
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# 🆔 Default Primary Key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

















