# Generated by Django 5.2.1 on 2025-10-28 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerdetailed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, help_text='Auto-filled from selected customer', max_length=254, verbose_name='Email Address')),
                ('customer_phone', models.CharField(blank=True, help_text='Auto-filled from selected customer', max_length=20, verbose_name='Phone Number')),
                ('customer_company', models.CharField(blank=True, help_text='Auto-filled from selected customer', max_length=100, verbose_name='Company Name')),
                ('source', models.CharField(blank=True, choices=[('organic', 'Organic Search'), ('paid_ads', 'Paid Ads'), ('social', 'Social Media'), ('email', 'Email Campaign'), ('referral', 'Referral'), ('event', 'Event/Trade Show'), ('website', 'Website Form'), ('cold', 'Cold Call/Email'), ('affiliate', 'Affiliate Marketing'), ('content', 'Content Marketing'), ('sms', 'SMS Campaign'), ('chatbot', 'Chatbot Interaction'), ('partner', 'Channel Partner'), ('retargeting', 'Retargeting Campaign'), ('video', 'Video Marketing'), ('inbound_call', 'Inbound Call'), ('outbound_call', 'Outbound Call'), ('direct_mail', 'Direct Mail'), ('app', 'Mobile App'), ('demo', 'Product Demo'), ('survey', 'Survey Response'), ('linkedin', 'LinkedIn Outreach'), ('youtube', 'YouTube Channel'), ('podcast', 'Podcast Mention'), ('forum', 'Online Forum or Community')], help_text='How this lead was acquired', max_length=30, verbose_name='Lead Source')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('rejected', 'Rejected')], help_text='Current status of the lead', max_length=20, verbose_name='Lead Status')),
                ('notes', models.TextField(blank=True, help_text='Any extra information about the lead', verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the lead was created', verbose_name='Created At')),
                ('created_by', models.ForeignKey(help_text='User who added this lead', on_delete=django.db.models.deletion.CASCADE, related_name='created_leads', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer_name', models.ForeignKey(blank=True, help_text='Select an existing customer to link this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_customer_name', to='customerdetailed.customerdetailed', verbose_name='Customer Name')),
            ],
            options={
                'verbose_name': 'Lead Entry',
                'verbose_name_plural': 'Lead Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
